version: '2'

services:
  dogecoin:
    extends:
      file: docker-compose.tmpl.yml
      service: dogecoin-base-mainnet

  dogecoin-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: dogecoin-base-testnet

  addrindexrs-dc:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-dc-base-mainnet

  addrindexrs-dc-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-dc-base-testnet

  dogeparty:
    extends:
      file: docker-compose.tmpl.yml
      service: dogeparty-base-mainnet
    links:
      - dogecoin
      - addrindexrs-dc

  dogeparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: dogeparty-base-testnet
    links:
      - dogecoin-testnet
      - addrindexrs-dc-testnet

  mongodb:
    extends:
      file: docker-compose.tmpl.yml
      service: mongodb-base

  redis:
    extends:
      file: docker-compose.tmpl.yml
      service: redis-base

  dogeblock:
    extends:
      file: docker-compose.tmpl.yml
      service: dogeblock-base-mainnet
    links:
      - dogecoin
      - dogeparty
      - mongodb
      - redis

  dogeblock-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: dogeblock-base-testnet
    links:
      - dogecoin-testnet
      - dogeparty-testnet
      - mongodb
      - redis
  
  dogewallet:
    extends:
      file: docker-compose.tmpl.yml
      service: dogewallet-base
    links:
      - redis
      - dogeblock
      - dogeblock-testnet

  http-addrindexrs-dc:
    extends:
      file: docker-compose.tmpl.yml
      service: http-addrindexrs-dc-base-mainnet
    links:
      - dogecoin
      - addrindexrs-dc
      
  http-addrindexrs-dc-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: http-addrindexrs-dc-base-testnet
    links:
      - dogecoin-testnet
      - addrindexrs-dc-testnet    
volumes:
  dogecoin-data:
  addrindexrs-dc-data:
  dogeparty-data:
  dogeblock-data:
  mongodb-data:
  #armory-data: